<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllTasksByPostmanId($postmanId){
        $taskRepository = $this->getDoctrine()->getRepository('AppBundle:Task');
        $tasks = $taskRepository->findByPostman($postmanId);
        $view = $this->view($tasks, 200);
        return $this->handleView($view);
    }
}
