app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_api:
    resource: "@AppBundle/Resources/config/routing.yml"
    type:     rest

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
